# Generated by Django 3.1.1 on 2020-11-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20201106_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistticket',
            old_name='user',
            new_name='user_id',
        ),
    ]
