# Generated by Django 3.1.1 on 2020-11-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_auto_20201106_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistticket',
            name='checkin_date',
        ),
        migrations.AddField(
            model_name='waitlistticket',
            name='check_in_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
