# Generated by Django 3.1.1 on 2020-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0005_auto_20201106_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistticket',
            name='customer_is_served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlistticket',
            name='table_is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
