# Generated by Django 3.1.1 on 2020-11-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0006_auto_20201109_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistticket',
            name='check_in_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
